import { StyleSheet, Dimensions } from 'react-native';
import { RFValue } from 'react-native-responsive-fontsize';
import { BOLD, SEMIBOLD, REGULAR } from '../../constants/fontfamily';
import { HEIGHT } from '../../constants/config';

const { width: WIDTH } = Dimensions.get('window');
const DAY_SIZE = Math.floor((WIDTH * 0.1) / 2) * 2;

const getStyles = colors =>
  StyleSheet.create({
    container: { flex: 1, backgroundColor: colors.background },
    header: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingHorizontal: '5%',
      paddingVertical: RFValue(15),
      borderBottomWidth: 1,
      borderColor: colors.border,
    },
    backBtn: {
      padding: RFValue(5),
      alignItems: 'center',
      justifyContent: 'center',
    },
    headerActions: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: RFValue(4),
    },
    headerTitle: {
      fontFamily: BOLD,
      fontSize: RFValue(14),
      color: colors.text,
    },
    content: {
      paddingHorizontal: '5%',
      paddingBottom: RFValue(40),
      paddingTop: RFValue(20),
    },
    titleSection: { alignItems: 'center', marginBottom: RFValue(30) },
    iconCircle: {
      width: RFValue(72),
      height: RFValue(72),
      borderRadius: RFValue(36),
      justifyContent: 'center',
      alignItems: 'center',
      marginBottom: RFValue(16),
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.15,
      shadowRadius: 8,
      elevation: 6,
    },
    categoryBadge: {
      borderWidth: 1,
      paddingHorizontal: RFValue(12),
      paddingVertical: RFValue(6),
      borderRadius: RFValue(20),
      marginBottom: RFValue(12),
    },
    categoryText: {
      color: colors.primary,
      fontFamily: SEMIBOLD,
      fontSize: RFValue(11),
    },
    habitTitle: {
      fontFamily: BOLD,
      fontSize: RFValue(20),
      color: colors.text,
      marginBottom: RFValue(8),
      textAlign: 'center',
    },
    scheduleText: {
      fontFamily: REGULAR,
      fontSize: RFValue(11),
      color: colors.textSecondary,
    },
    statsGrid: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      marginBottom: RFValue(30),
    },
    statCard: {
      flex: 1,
      backgroundColor: colors.surface,
      borderRadius: RFValue(12),
      padding: RFValue(16),
      marginHorizontal: RFValue(5),
      borderWidth: 1,
      borderColor: colors.border,
      alignItems: 'center',
    },
    statLabel: {
      fontFamily: SEMIBOLD,
      fontSize: RFValue(10),
      color: colors.textSecondary,
      marginBottom: RFValue(8),
    },
    statValue: { fontFamily: BOLD, fontSize: RFValue(22), color: colors.text },
    statSub: {
      fontSize: RFValue(12),
      color: colors.textSecondary,
      fontFamily: REGULAR,
    },
    section: { marginBottom: RFValue(30) },
    sectionTitle: {
      fontFamily: BOLD,
      fontSize: RFValue(14),
      color: colors.text,
      marginBottom: RFValue(20),
    },
    timelineContainer: { marginLeft: RFValue(10) },
    timelineRow: { flexDirection: 'row', minHeight: RFValue(70) },
    timelineIndicator: {
      alignItems: 'center',
      width: RFValue(30),
      marginRight: RFValue(15),
    },
    timelineLine: {
      width: 2,
      flex: 1,
      backgroundColor: colors.border,
      marginVertical: RFValue(4),
    },
    timelineContent: {
      flex: 1,
      paddingBottom: RFValue(15),
      paddingTop: RFValue(2),
    },
    timelineHeaderRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: RFValue(4),
    },
    timelineDate: {
      fontFamily: BOLD,
      fontSize: RFValue(12),
      color: colors.text,
    },
    timelineStatus: {
      fontFamily: SEMIBOLD,
      fontSize: RFValue(11),
      color: colors.textSecondary,
    },
    timelineMetric: {
      fontFamily: SEMIBOLD,
      fontSize: RFValue(12),
      color: colors.primary,
      marginBottom: RFValue(8),
    },
    notesBox: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: colors.background,
      padding: RFValue(10),
      borderRadius: RFValue(8),
      marginTop: RFValue(10),
    },
    notesText: {
      fontFamily: REGULAR,
      fontSize: RFValue(11),
      color: colors.textSecondary,
      marginLeft: RFValue(8),
      flex: 1,
    },
    noteContainer: {
      backgroundColor: colors.surface,
      borderRadius: WIDTH * 0.02,
      marginTop: HEIGHT * 0.01,
      borderWidth: 1,
      borderColor: colors.border,
      overflow: 'hidden',
    },
    noteHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingHorizontal: RFValue(10),
      paddingVertical: RFValue(6),
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
    },
    noteTitle: {
      fontFamily: SEMIBOLD,
      fontSize: RFValue(12),
      color: colors.text,
    },
    noteContent: {
      fontFamily: REGULAR,
      fontSize: RFValue(11),
      color: colors.textSecondary,
      padding: RFValue(10),
    },
    actionsRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: HEIGHT * 0.02,
      gap: RFValue(8),
    },
    actionBtn: {
      flex: 1,
      flexDirection: 'column',
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.surface,
      paddingVertical: RFValue(10),
      borderRadius: RFValue(12),
      borderWidth: 1,
      borderColor: colors.border,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.05,
      shadowRadius: 4,
      elevation: 2,
      gap: RFValue(4),
    },
    actionBtnText: {
      fontFamily: SEMIBOLD,
      fontSize: RFValue(10),
      color: colors.text,
    },

    calendarCard: {
      backgroundColor: colors.surface,
      borderRadius: RFValue(16),
      position: 'relative', // for overlay
    },
    actionSheetOverlay: {
      position: 'absolute',
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      backgroundColor: 'rgba(255, 255, 255, 0.1)',
      justifyContent: 'center',
      alignItems: 'center',
      borderRadius: RFValue(16),
      zIndex: 10,
    },
    customDayWrapper: {
      width: '100%',
      alignItems: 'center',
    },
    customDay: {
      width: DAY_SIZE,
      height: DAY_SIZE,
      borderRadius: DAY_SIZE / 2,
      justifyContent: 'center',
      alignItems: 'center',
      marginHorizontal: WIDTH * 0.01,
    },
    customDaySelected: {
      backgroundColor: colors.primary,
      shadowColor: colors.primary,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.3,
      shadowRadius: 6,
      elevation: 4,
    },
    customDayToday: {
      backgroundColor: `${colors.primary}15`,
      borderWidth: 1,
      borderColor: colors.primary,
    },
    customDayText: {
      fontFamily: SEMIBOLD,
      fontSize: RFValue(11),
      color: colors.text,
    },
    customDayTextSelected: {
      color: colors.surface,
    },
    customDayTextToday: {
      color: colors.primary,
    },
    customDayTextDisabled: {
      color: colors.border, // light gray
    },
    customDayDot: {
      width: RFValue(4),
      height: RFValue(4),
      borderRadius: RFValue(2),
      backgroundColor: colors.primary,
      marginTop: RFValue(2),
      position: 'absolute',
      bottom: RFValue(4),
    },
    customDayDotSelected: {
      backgroundColor: colors.surface,
    },

    actionSheetContainer: {
      borderTopLeftRadius: RFValue(24),
      borderTopRightRadius: RFValue(24),
      paddingBottom: RFValue(20),
      backgroundColor: colors.surface,
    },
    actionSheetScroll: { padding: RFValue(20) },
    modalHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: RFValue(8),
    },
    modalTitle: { fontFamily: BOLD, fontSize: RFValue(16), color: colors.text },
    modalSubtitle: {
      fontFamily: REGULAR,
      fontSize: RFValue(11),
      color: colors.textSecondary,
      marginBottom: RFValue(20),
    },

    // ── Visual Schedule Styles ──────────────────────────────────────────────
    scheduleVisualContainer: {
      flexDirection: 'row',
      justifyContent: 'center',
      alignItems: 'center',
      marginTop: RFValue(12),
      marginBottom: RFValue(4),
      flexWrap: 'wrap',
      gap: RFValue(8),
    },
    scheduleDayCircle: {
      width: RFValue(30),
      height: RFValue(30),
      borderRadius: RFValue(15),
      backgroundColor: colors.surface,
      borderWidth: 1,
      borderColor: colors.border,
      justifyContent: 'center',
      alignItems: 'center',
    },
    scheduleDayText: {
      fontFamily: SEMIBOLD,
      fontSize: RFValue(10),
      color: colors.textSecondary,
    },
    scheduleDayActiveText: {
      color: colors.surface,
    },
    schedulePeriodBadge: {
      paddingHorizontal: RFValue(16),
      paddingVertical: RFValue(8),
      borderRadius: RFValue(20),
      backgroundColor: `${colors.primary}15`,
      borderWidth: 1,
      borderColor: `${colors.primary}30`,
    },
    schedulePeriodText: {
      fontFamily: SEMIBOLD,
      fontSize: RFValue(12),
      color: colors.primary,
    },

    // ── Checklist Styles ────────────────────────────────────────────────────
    checklistContainer: {
      marginTop: RFValue(10),
      backgroundColor: colors.surface,
      borderRadius: RFValue(12),
      padding: RFValue(16),
      borderWidth: 1,
      borderColor: colors.border,
      marginBottom: RFValue(20),
    },
    checklistItem: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingVertical: RFValue(10),
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
    },
    checklistItemLast: {
      borderBottomWidth: 0,
      paddingBottom: 0,
    },
    checklistText: {
      fontFamily: REGULAR,
      fontSize: RFValue(13),
      color: colors.text,
      marginLeft: RFValue(12),
      flex: 1,
    },
    checklistTextCompleted: {
      color: colors.textSecondary,
      textDecorationLine: 'line-through',
    },

    // ── Completion Action Sheet Styles ──────────────────────────────────────
    sheetHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      padding: RFValue(20),
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
    },
    sheetTitle: { fontFamily: BOLD, fontSize: RFValue(16), color: colors.text },
    sheetCloseBtn: { padding: RFValue(5) },
    sheetContent: { padding: RFValue(20) },
    habitItemContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: RFValue(24),
      backgroundColor: colors.background,
      padding: RFValue(12),
      borderRadius: RFValue(12),
    },
    habitIconBg: {
      width: RFValue(44),
      height: RFValue(44),
      borderRadius: RFValue(22),
      justifyContent: 'center',
      alignItems: 'center',
      marginRight: RFValue(12),
    },
    habitItemTitle: {
      fontFamily: BOLD,
      fontSize: RFValue(13),
      color: colors.text,
    },
    habitItemSub: {
      fontFamily: REGULAR,
      fontSize: RFValue(11),
      color: colors.textSecondary,
      marginTop: RFValue(2),
    },
    inputGroup: { marginBottom: RFValue(20) },
    inputLabel: {
      fontFamily: SEMIBOLD,
      fontSize: RFValue(12),
      color: colors.text,
      marginBottom: RFValue(8),
    },
    metricInputContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: RFValue(12),
      paddingHorizontal: RFValue(12),
      backgroundColor: colors.background,
    },
    metricInput: {
      flex: 1,
      height: RFValue(46),
      fontFamily: SEMIBOLD,
      fontSize: RFValue(15),
      color: colors.text,
    },
    metricUnit: {
      fontFamily: REGULAR,
      fontSize: RFValue(13),
      color: colors.textSecondary,
      marginLeft: RFValue(8),
    },
    moodContainer: { flexDirection: 'row', justifyContent: 'space-between' },
    moodBtn: {
      flex: 1,
      height: RFValue(46),
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: RFValue(12),
      justifyContent: 'center',
      alignItems: 'center',
      marginHorizontal: RFValue(4),
      backgroundColor: colors.background,
    },
    moodBtnActive: {
      borderColor: colors.primary,
      backgroundColor: `${colors.primary}10`,
    },
    moodText: {
      fontFamily: SEMIBOLD,
      fontSize: RFValue(12),
      color: colors.textSecondary,
    },
    moodTextActive: { color: colors.primary },
    notesInput: {
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: RFValue(12),
      padding: RFValue(12),
      height: RFValue(80),
      fontFamily: REGULAR,
      fontSize: RFValue(13),
      color: colors.text,
      textAlignVertical: 'top',
      backgroundColor: colors.background,
    },
    saveBtn: {
      backgroundColor: colors.primary,
      height: RFValue(50),
      borderRadius: RFValue(25),
      justifyContent: 'center',
      alignItems: 'center',
      marginTop: RFValue(10),
    },
    saveBtnText: {
      fontFamily: BOLD,
      fontSize: RFValue(14),
      color: colors.surface,
    },
  });

export default getStyles;
