import { StyleSheet } from 'react-native';
import { RFValue } from 'react-native-responsive-fontsize';
import {
  BLACK,
  GRAY9,
  INPUT_BORDER,
  PRIMARY_OS,
  WHITE,
} from '../../constants/color';
import { HEIGHT } from '../../constants/config';
import { INTER, SEMIBOLD } from '../../constants/fontfamily';

export default StyleSheet.create({
  container: { flex: 1, backgroundColor: WHITE },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: '5%',
    paddingVertical: HEIGHT * 0.015,
    borderBottomWidth: 1,
    borderColor: INPUT_BORDER,
  },
  backBtn: { padding: 5, width: 50 },
  backText: { fontFamily: INTER, fontSize: RFValue(14), color: BLACK },
  headerTitle: { fontFamily: SEMIBOLD, fontSize: RFValue(16), color: BLACK },
  content: {
    paddingHorizontal: '5%',
    paddingBottom: HEIGHT * 0.15,
    paddingTop: 20,
  },
  section: { marginBottom: HEIGHT * 0.03 },
  inputContainer: { marginBottom: HEIGHT * 0.03 },
  label: {
    fontFamily: SEMIBOLD,
    fontSize: RFValue(14),
    color: BLACK,
    marginBottom: 10,
  },
  input: {
    borderWidth: 1,
    borderColor: INPUT_BORDER,
    borderRadius: 12,
    padding: 15,
    fontFamily: INTER,
    fontSize: RFValue(14),
    color: BLACK,
    backgroundColor: '#F9FAFB',
  },
  catScroll: { flexDirection: 'row' },
  chip: {
    borderWidth: 1,
    borderColor: INPUT_BORDER,
    borderRadius: 20,
    paddingHorizontal: 16,
    paddingVertical: 8,
    marginRight: 10,
  },
  chipActive: { backgroundColor: PRIMARY_OS, borderColor: PRIMARY_OS },
  chipText: { fontFamily: INTER, fontSize: RFValue(12), color: BLACK },
  chipTextActive: { color: WHITE },
  scheduleGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
  },
  scheduleBtn: {
    width: '48%',
    paddingVertical: 12,
    borderWidth: 1,
    borderColor: INPUT_BORDER,
    borderRadius: 10,
    alignItems: 'center',
    marginBottom: 10,
  },
  scheduleBtnActive: { backgroundColor: '#DBEAFE', borderColor: PRIMARY_OS },
  scheduleBtnText: { fontFamily: INTER, fontSize: RFValue(12), color: BLACK },
  scheduleBtnTextActive: { color: PRIMARY_OS, fontFamily: SEMIBOLD },
  dynamicScheduleBox: {
    backgroundColor: WHITE,
    padding: 15,
    borderRadius: 10,
    marginTop: 10,
  },
  row: { flexDirection: 'row', alignItems: 'center', marginTop: 10 },
  smallInput: {
    borderWidth: 1,
    borderColor: INPUT_BORDER,
    borderRadius: 8,
    width: 50,
    textAlign: 'center',
    padding: 8,
    fontFamily: INTER,
  },
  dynamicText: { fontFamily: INTER, fontSize: RFValue(13), color: BLACK },
  dropdownBtn: {
    borderWidth: 1,
    borderColor: INPUT_BORDER,
    borderRadius: 8,
    padding: 8,
  },
  addBtn: {
    backgroundColor: WHITE,
    borderRadius: 12,
    padding: 15,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: INPUT_BORDER,
    borderStyle: 'dashed',
  },
  addBtnText: { fontFamily: SEMIBOLD, fontSize: RFValue(13), color: GRAY9 },
  settingRow: {
    backgroundColor: WHITE,
    padding: 15,
    borderRadius: 12,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  settingTitle: { fontFamily: SEMIBOLD, fontSize: RFValue(13), color: BLACK },
  settingSub: {
    fontFamily: INTER,
    fontSize: RFValue(10),
    color: GRAY9,
    marginTop: 4,
  },
  toggle: {
    width: 40,
    height: 24,
    borderRadius: 12,
    backgroundColor: INPUT_BORDER,
  },
  bottomBar: {
    position: 'absolute',
    bottom: 0,
    width: '100%',
    backgroundColor: WHITE,
    borderTopWidth: 1,
    borderColor: INPUT_BORDER,
    paddingHorizontal: '5%',
    paddingTop: 15,
  },
  saveBtn: {
    backgroundColor: PRIMARY_OS,
    borderRadius: 12,
    paddingVertical: 15,
    alignItems: 'center',
  },
  saveBtnText: { fontFamily: SEMIBOLD, fontSize: RFValue(14), color: WHITE },
});
