import { StyleSheet } from 'react-native';
import { RFValue } from 'react-native-responsive-fontsize';
import { HEIGHT } from '../../constants/config';
import { BOLD, SEMIBOLD, INTER } from '../../constants/fontfamily';

const getStyles = (colors) => StyleSheet.create({
  container: { flex: 1, backgroundColor: colors.surface },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: '5%',
    paddingVertical: HEIGHT * 0.015,
    borderBottomWidth: 1,
    borderColor: colors.border,
  },
  backBtn: { padding: 5, width: 50 },
  backText: { fontFamily: INTER, fontSize: RFValue(14), color: colors.text },
  headerTitle: { fontFamily: SEMIBOLD, fontSize: RFValue(16), color: colors.text },
  content: {
    paddingHorizontal: '5%',
    paddingBottom: HEIGHT * 0.15,
    paddingTop: 20,
  },
  section: { marginBottom: HEIGHT * 0.03 },
  inputContainer: { marginBottom: HEIGHT * 0.03 },
  label: {
    fontFamily: SEMIBOLD,
    fontSize: RFValue(14),
    color: colors.text,
    marginBottom: 10,
  },
  input: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 12,
    padding: 15,
    fontFamily: INTER,
    fontSize: RFValue(14),
    color: colors.text,
    backgroundColor: colors.background,
  },
  catScroll: { flexDirection: 'row' },
  chip: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 20,
    paddingHorizontal: 16,
    paddingVertical: 8,
    marginRight: 10,
  },
  chipActive: { backgroundColor: colors.primary, borderColor: colors.primary },
  chipText: { fontFamily: INTER, fontSize: RFValue(12), color: colors.text },
  chipTextActive: { color: colors.surface },
  scheduleGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
  },
  scheduleBtn: {
    width: '48%',
    paddingVertical: 12,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 10,
    alignItems: 'center',
    marginBottom: 10,
  },
  scheduleBtnActive: { backgroundColor: '#DBEAFE', borderColor: colors.primary },
  scheduleBtnText: { fontFamily: INTER, fontSize: RFValue(12), color: colors.text },
  scheduleBtnTextActive: { color: colors.primary, fontFamily: SEMIBOLD },
  dynamicScheduleBox: {
    backgroundColor: colors.surface,
    padding: 15,
    borderRadius: 10,
    marginTop: 10,
  },
  row: { flexDirection: 'row', alignItems: 'center', marginTop: 10 },
  smallInput: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 8,
    width: 50,
    textAlign: 'center',
    padding: 8,
    fontFamily: INTER,
  },
  dynamicText: { fontFamily: INTER, fontSize: RFValue(13), color: colors.text },
  dropdownBtn: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 8,
    padding: 8,
  },
  addBtn: {
    backgroundColor: colors.surface,
    borderRadius: 12,
    padding: 15,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: colors.border,
    borderStyle: 'dashed',
  },
  addBtnText: { fontFamily: SEMIBOLD, fontSize: RFValue(13), color: colors.textSecondary },
  settingRow: {
    backgroundColor: colors.surface,
    padding: 15,
    borderRadius: 12,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  settingTitle: { fontFamily: SEMIBOLD, fontSize: RFValue(13), color: colors.text },
  settingSub: {
    fontFamily: INTER,
    fontSize: RFValue(10),
    color: colors.textSecondary,
    marginTop: 4,
  },
  toggle: {
    width: 40,
    height: 24,
    borderRadius: 12,
    backgroundColor: colors.border,
  },
  bottomBar: {
    position: 'absolute',
    bottom: 0,
    width: '100%',
    backgroundColor: colors.surface,
    borderTopWidth: 1,
    borderColor: colors.border,
    paddingHorizontal: '5%',
    paddingTop: 15,
  },
  saveBtn: {
    backgroundColor: colors.primary,
    borderRadius: 12,
    paddingVertical: 15,
    alignItems: 'center',
  },
  saveBtnText: { fontFamily: SEMIBOLD, fontSize: RFValue(14), color: colors.surface },
});

export default getStyles;
